name: 'Add labels to issues and pull requests'
on:
  issues:
    types: [ opened ]

  pull_request_target:
    branches: [ 'main*', 'instrumentation*', 'exporter*', 'extensions*' ]

permissions:
  contents: read

jobs:
  add-labels-on-issues:
    permissions:
      issues: write
    if: github.event_name == 'issues' && !github.event.issue.pull_request

    runs-on: ubuntu-24.04

    steps:
      - name: check out code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Add labels for component found in bug issue descriptions
        shell: pwsh
        run: |
          Import-Module .\build\scripts\add-labels.psm1

          AddLabelsOnIssuesForComponentFoundInBody `
            -issueNumber ${env:ISSUE_NUMBER} `
            -issueLabels ${env:ISSUE_LABELS} `
            -issueBody ${env:ISSUE_BODY}
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ',') }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}

  add-labels-on-pull-requests:
    permissions:
      pull-requests: write
    if: github.event_name == 'pull_request_target'

    runs-on: ubuntu-24.04

    steps:
      - name: check out code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          ref: ${{ github.event.repository.default_branch }} # Note: Do not run on the PR branch we want to execute add-labels.psm1 from main on the base repo only because pull_request_target can see secrets

      - name: Add labels for files changed on pull requests
        shell: pwsh
        run: |
          Import-Module .\build\scripts\add-labels.psm1

          AddLabelsOnPullRequestsBasedOnFilesChanged `
            -pullRequestNumber ${env:PR_NUMBER} `
            -labelPackagePrefix 'comp:'
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
