name: Publish AOTCompatibility testApp

on:
  pull_request:
    branches: [ 'main*' ]
    paths:
    - 'src/OpenTelemetry.Instrumentation.Runtime/**'
    - '!src/OpenTelemetry.Instrumentation.Runtime/README.md'
    - 'src/OpenTelemetry.Instrumentation.EventCounters/**'
    - '!src/OpenTelemetry.Instrumentation.EventCounters/README.md'

jobs:
  aot-test:
    strategy:
      fail-fast: false # ensures the entire test matrix is run, even if one permutation fails
      matrix:
        os: [ ubuntu-latest ]
        version: [ net7.0 ]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: publish AOT testApp, assert static analysis warning count, and run the app
      shell: pwsh
      run: .\build\test-aot-compatibility.ps1 ${{ matrix.version }}

