name: Build OpenTelemetry.Instrumentation.Process

on:
  pull_request:
    branches: [ 'main*', 'instrumentation*' ]
    paths:
    - '.github/**'
    - 'build/**'
    - 'src/OpenTelemetry.Instrumentation.Process.Tests/**'
    - 'src/OpenTelemetry.Internal/**'
    - 'src/Directory.Build.props'
    - 'src/Directory.Build.targets'
    - 'test/OpenTelemetry.Instrumentation.Process.Tests/**'
    - 'global.json'
    - 'NuGet.config'

jobs:
  build-test:

    strategy:
      fail-fast: false # ensures the entire test matrix is run, even if one permutation fails
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        version: [ net462, netcoreapp3.1, net6.0, net7.0 ]
        exclude:
        - os: ubuntu-latest
          version: net462

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Install .NET 3.1 SDK
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: '3.1.x'

    - name: Install .NET 7 SDK
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: '7.0.x'

    - name: Build
      run: dotnet build --configuration Release test/OpenTelemetry.Instrumentation.Process.Tests/OpenTelemetry.Instrumentation.Process.Tests.csproj

    - name: Test ${{ matrix.version }}
      run: dotnet test test/OpenTelemetry.Instrumentatio
  n.Process.Tests/bin/Release/${{ matrix.version }}/OpenTelemetry.Instrumentation.Process.Tests.dll --logger:"console;verbosity=detailed"
