name: Core version update

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: 'Release tag'
        type: string

jobs:
  automation:
    uses: ./.github/workflows/automation.yml
    secrets: inherit

  core-version-update:
    runs-on: ubuntu-latest

    needs: automation

    if: needs.automation.outputs.enabled

    env:
      GH_TOKEN: ${{ secrets[needs.automation.outputs.token-secret-name] }}

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.repository.default_branch }}
        token: ${{ secrets[needs.automation.outputs.token-secret-name] }}
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4

    - name: Create GitHub Pull Request to update core version in props and update CHANGELOGs in projects
      shell: pwsh
      run: |
        Import-Module .\build\scripts\post-release.psm1

        CreateOpenTelemetryCoreLatestVersionUpdatePullRequest `
          -gitRepository '${{ github.repository }}' `
          -tag '${{ inputs.tag }}' `
          -targetBranch '${{ github.event.repository.default_branch }}' `
          -gitUserName '${{ needs.automation.outputs.username }}' `
          -gitUserEmail '${{ needs.automation.outputs.email }}'
