name: Lint - dotnet format

on:
  workflow_call:

permissions:
  contents: read

jobs:
  run-dotnet-format:
    runs-on: windows-latest

    steps:
    - name: check out code
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

    - name: Setup .NET
      uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602 # v5.0.1

    - name: dotnet format
      run: dotnet format opentelemetry-dotnet-contrib.slnx --verify-no-changes
