name: Pack OpenTelemetry.ResourceDetectors.ProcessRuntime

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'ResourceDetectors.ProcessRuntime-*' # trigger when we create a tag with prefix "ResourceDetectors.ProcessRuntime-"

jobs:
  call-build-test-pack:
    permissions:
      contents: write
    uses: ./.github/workflows/Component.Package.yml
    with:
      project-name: OpenTelemetry.ResourceDetectors.ProcessRuntime
    secrets: inherit
