name: Pack OpenTelemetry.Contrib.Instrumentation.MassTransit

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'Instrumentation.MassTransit-*' # trigger when we create a tag with prefix "Instrumentation.MassTransit-"

jobs:
  build-test-pack:
    runs-on: ${{ matrix.os }}
    env:
      PROJECT: OpenTelemetry.Contrib.Instrumentation.MassTransit

    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # fetching all

    - name: Install dependencies
      run: dotnet restore

    - name: dotnet build ${{env.PROJECT}}
      run: dotnet build src/${{env.PROJECT}} --configuration Release --no-restore -p:Deterministic=true

    - name: dotnet test ${{env.PROJECT}}
      run: dotnet test test/${{env.PROJECT}}.Tests

    - name: dotnet pack ${{env.PROJECT}}
      run: dotnet pack src/${{env.PROJECT}} --configuration Release --no-build

    - name: Publish Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{env.PROJECT}}-packages
        path: '**/${{env.PROJECT}}/bin/**/*.*nupkg'

    - name: Publish Nuget
      run: |
        nuget setApiKey ${{ secrets.NUGET_TOKEN }} -Source https://api.nuget.org/v3/index.json
        nuget push **/${{env.PROJECT}}/bin/**/*.nupkg -Source https://api.nuget.org/v3/index.json