name: Lint - YAML

on:
  workflow_call:

jobs:
  run-yamllint:
    runs-on: ubuntu-latest

    steps:
    - name: check out code
      uses: actions/checkout@v4

    - name: install yamllint
      run: pip install yamllint

    - name: run yamllint
      run: yamllint .
