name: Lint - YAML

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-yamllint:
    runs-on: ubuntu-22.04

    steps:
    - name: check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: install yamllint
      run: pip install -r ./build/yamllint-requirements.txt --require-hashes

    - name: run yamllint
      run: yamllint --no-warnings .
